### ISSUE TITLE
[Bug] Step "Run markdown lint" ends with en error

### ISSUE THREAD

**Issue by ricardojfc** [skills/test-with-actions#44]
### Summary

Step "Run markdown lint" ends with en error and the `README.md` isn't updated

### How to reproduce

1. Open a new browser tab, and work on the steps in your second tab while you read the instructions in this tab
2. Go to the **Actions tab**.
3. Click **New workflow**.
4. Search for "Simple workflow" and click **Configure**.
5. Name your workflow `ci.yml`.
6. Update the workflow to remove all steps other than the "checkout" step.
7. Add the following step to your workflow:
    
    ```yaml
    - name: Run markdown lint
      run: |
        npm install remark-cli remark-preset-lint-consistent
        npx remark . --use remark-preset-lint-consistent --frail
    ```
    
    > Even after the code is indented properly in `ci.yml`, you will see a build error in GitHub Actions. We'll fix this in the next step.
    
8. Click **Start commit**, and choose to make a new branch named `ci`.
9. Click **Propose a new file**.
10. Click **Create pull request**.
11. Wait about 20 seconds then refresh this page (the one you're following instructions from). [GitHub Actions](https://docs.github.com/en/actions) will automatically update to the next step.

![Image](https://github.com/skills/test-with-actions/assets/112181786/0d74da0b-1acc-499b-9d0a-4340913f5d0a)
