### ISSUE TITLE
[Bug] No errors generated in step 1 to be resolved in step 2

### ISSUE THREAD

**Issue by ananuness** [skills/test-with-actions#67]
### Summary

It is expected that in the first step, we will have an error generated to resolve, but mine does not generate any error. I appreciate any help!

### How to reproduce

1. Go to the **Actions tab**.
2. Click **New workflow**.
3. Search for "Simple workflow" and click **Configure**.
4. Name your workflow `ci.yml`.
5. Update the workflow by deleting the last two steps.
6. Add the following step at the end of your workflow:
   ```yml
   - name: Run markdown lint
     run: |
       npm install remark-cli remark-preset-lint-consistent
       npx remark . --use remark-preset-lint-consistent --frail
   ```

My `ci.yml`:
![image](https://github.com/skills/test-with-actions/assets/51466624/eab31b7e-50ba-4acc-b42c-4eec82fd3946)

No error when the pull request is created: 
![image](https://github.com/skills/test-with-actions/assets/51466624/9e6d9a7c-2930-43ec-acd7-417740616bd4)
